firstname = input("Enter First Name: ")
lastname = input("Enter Last Name: ")
middlename = input("Enter Middle Name: ")
birthday = input("Enter your Birthday (mm/dd/yyyy): ")
gender = input("Male or Female: ")
address = input("Enter your Address: ")
course = input("Enter your Course: ")
yearlevel = input("Enter your Year Level: ") 
print("Name:" , firstname)
print("Last Name: ", lastname)
print("Middle Name: ", middlename)
print("Birthday: ", birthday)
print("Gender: ",gender)
print("Address: ", address)
print("Course: ", course)
print("Year Level: ", yearlevel)
print("Thank you for answering the questions!")